# Generated by Django 4.1 on 2023-03-20 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_shop', '0006_dynamicsitesettings_delivery_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('1', 'Обычная доставка'), ('2', 'Экспресс-доставка ')], max_length=50, verbose_name='тип доставки')),
                ('city', models.CharField(max_length=50, verbose_name='город доставки')),
                ('address', models.TextField(verbose_name='адрес доставки')),
                ('delivery_cost', models.IntegerField(verbose_name='стоимость доставки')),
            ],
            options={
                'verbose_name': 'доставка',
                'verbose_name_plural': 'доставки',
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='статус оплаты')),
                ('card_num', models.CharField(max_length=8, verbose_name='номер карты')),
                ('payment_type', models.CharField(choices=[('1', 'Онлайн картой'), ('2', 'Онлайн со случайного чужого счёта')], max_length=50, verbose_name='способ оплаты')),
            ],
            options={
                'verbose_name': 'оплата',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата заказа')),
                ('amount', models.IntegerField(verbose_name='общая сумма заказа')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='payment.delivery')),
                ('goods', models.ManyToManyField(to='app_shop.catalog')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='payment.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'orders',
            },
        ),
    ]
