# Generated by Django 4.1 on 2023-03-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_order_goods_orderstogoods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderstogoods',
            table='orders_to_good',
        ),
    ]
