# Generated by Django 4.1 on 2023-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_orderstogoods_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_num',
            field=models.CharField(max_length=9, verbose_name='номер карты'),
        ),
    ]
