# Generated by Django 4.1 on 2022-10-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(max_length=30, null=True, verbose_name='отчество'),
        ),
        migrations.AddIndex(
            model_name='goodcategory',
            index=models.Index(fields=['name'], name='good_catego_name_78a25c_idx'),
        ),
    ]
