# Generated by Django 4.1 on 2022-10-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_alter_userprofile_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='цена на товар')),
                ('discount', models.IntegerField(default=0, verbose_name='скидка на товар')),
                ('count', models.IntegerField(verbose_name='кол-во товара')),
            ],
            options={
                'verbose_name': 'каталог',
                'verbose_name_plural': 'каталоги',
                'db_table': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='название товара')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.goodcategory', verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'good',
            },
        ),
        migrations.CreateModel(
            name='GoodTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название тега')),
                ('tags_to_good', models.ManyToManyField(to='app_shop.good', verbose_name='теги к товарам')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='CatalogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='files/', verbose_name='изображение')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_shop.catalog', verbose_name='каталог')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.good', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.shop', verbose_name='магазин'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['name', 'category'], name='good_name_59551b_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['good', 'shop'], name='catalog_good_id_98d0de_idx'),
        ),
    ]
