# Generated by Django 4.1 on 2022-10-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_catalog_good_goodtags_catalogimages_catalog_good_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='catalog',
            name='catalog_good_id_98d0de_idx',
        ),
        migrations.RemoveIndex(
            model_name='good',
            name='good_name_59551b_idx',
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['good'], name='catalog_good_id_cd12df_idx'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['category'], name='good_categor_71654e_idx'),
        ),
    ]
