# Generated by Django 4.1 on 2022-10-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_dynamicsitesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsitesettings',
            name='meta_content',
            field=models.CharField(default=2, max_length=256, verbose_name='meta_content'),
            preserve_default=False,
        ),
    ]
