# Generated by Django 4.1 on 2023-02-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_remove_specifications_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название характеристики')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='app_shop.goodcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
                'db_table': 'specifications',
            },
        ),
        migrations.CreateModel(
            name='SpecificationValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='значение характеристики')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_value', to='app_shop.specification', verbose_name='характеристика')),
            ],
            options={
                'verbose_name': 'значение характеристики',
                'verbose_name_plural': 'значения характеристик',
                'db_table': 'specification_values',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='specifications',
            field=models.ManyToManyField(to='app_shop.specificationvalues'),
        ),
    ]
