# Generated by Django 4.1 on 2023-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_specification_specificationvalues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsitesettings',
            name='delivery_cost',
            field=models.IntegerField(default=200, verbose_name='стоимость доставки'),
        ),
        migrations.AddField(
            model_name='dynamicsitesettings',
            name='express_delivery_cost',
            field=models.IntegerField(default=500, verbose_name='стоимость экспресс доставки'),
        ),
        migrations.AddField(
            model_name='dynamicsitesettings',
            name='order_cost',
            field=models.IntegerField(default=2000, verbose_name='стоимость заказа'),
        ),
    ]
