# Generated by Django 4.1 on 2022-10-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_dynamicsitesettings_meta_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicsitesettings',
            name='meta_content',
            field=models.CharField(default='page_content', max_length=256, verbose_name='meta_content'),
        ),
    ]
