# Generated by Django 4.1 on 2022-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_alter_dynamicsitesettings_meta_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsitesettings',
            name='cache_timeout',
            field=models.IntegerField(default=300, verbose_name='cache timeout'),
        ),
    ]
