# Generated by Django 4.1 on 2023-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_dynamicsitesettings_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='purchases_number',
            field=models.PositiveIntegerField(default=0, verbose_name='кол-во покупок'),
        ),
    ]
