# Generated by Django 4.1 on 2022-10-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_dynamicsitesettings_cache_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsitesettings',
            name='logo',
            field=models.ImageField(null=True, upload_to='site_images/', verbose_name='изображения сайта'),
        ),
    ]
