# Generated by Django 4.1 on 2022-12-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_manufacturer_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'производитель', 'verbose_name_plural': 'производители'},
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturer',
        ),
    ]
